package com.batch.fromdb;

import org.springframework.batch.item.file.FlatFileHeaderCallback;

import java.io.IOException;
import java.io.Writer;

/**
 * Created with IntelliJ IDEA.
 * User: TikuNibi
 * Date: 4/5/13
 * Time: 4:27 PM
 * To change this template use File | Settings | File Templates.
 */
public class LedgerHeaderCallback implements FlatFileHeaderCallback {

    public void writeHeader(Writer writer) throws IOException {
        //To change body of implemented methods use File | Settings | File Templates.
        writer.write("# Generated by FlatFileHeaderCallback");
    }
}
